// Error correction exercises — B1 / B2 / C1
// Each sentence has exactly ONE error. The user types the corrected word/phrase.

export const ERROR_CORRECTION_EXERCISES = [

  // ── B1 (12) ──────────────────────────────────────────────────────────────

  {
    id: 'err-1',
    level: 'B1',
    sentence: "She don't like coffee in the morning.",
    correction: "doesn't",
    errorWord: "don't",
    explanation: 'Third person singular (she/he/it) needs "doesn\'t", not "don\'t".',
    category: 'Present tenses',
  },
  {
    id: 'err-2',
    level: 'B1',
    sentence: 'He go to school by bus every day.',
    correction: 'goes',
    errorWord: 'go',
    explanation: 'Third person singular in present simple adds -es: "goes".',
    category: 'Present tenses',
  },
  {
    id: 'err-3',
    level: 'B1',
    sentence: 'Yesterday I have seen a great film.',
    correction: 'saw',
    errorWord: 'have seen',
    explanation: '"Yesterday" is a finished past time, so use simple past "saw", not present perfect.',
    category: 'Past tenses',
  },
  {
    id: 'err-4',
    level: 'B1',
    sentence: 'She was very boring at the party.',
    correction: 'bored',
    errorWord: 'boring',
    explanation: '"Boring" describes something that causes boredom. A person who feels bored is "bored".',
    category: 'Common mistakes',
  },
  {
    id: 'err-5',
    level: 'B1',
    sentence: 'I am agree with your opinion.',
    correction: 'agree',
    errorWord: 'am agree',
    explanation: '"Agree" is a verb, not an adjective. Use "I agree", not "I am agree".',
    category: 'Common mistakes',
  },
  {
    id: 'err-6',
    level: 'B1',
    sentence: 'She arrived to the airport late.',
    correction: 'at',
    errorWord: 'to',
    explanation: 'With "arrive", use "at" for specific places (airports, stations), not "to".',
    category: 'Prepositions',
  },
  {
    id: 'err-7',
    level: 'B1',
    sentence: 'I am here since three hours.',
    correction: 'for',
    errorWord: 'since',
    explanation: '"Since" is used with a point in time; "for" is used with a duration like "three hours".',
    category: 'Present tenses',
  },
  {
    id: 'err-8',
    level: 'B1',
    sentence: 'Can you give me an information about the train?',
    correction: 'some',
    errorWord: 'an',
    explanation: '"Information" is uncountable; it cannot take "an". Use "some information".',
    category: 'Articles',
  },
  {
    id: 'err-9',
    level: 'B1',
    sentence: 'She is listening music right now.',
    correction: 'to',
    errorWord: 'listening',
    explanation: 'The verb "listen" requires the preposition "to": "listening to music".',
    category: 'Prepositions',
  },
  {
    id: 'err-10',
    level: 'B1',
    sentence: 'He must to study harder for his exams.',
    correction: 'study',
    errorWord: 'to study',
    explanation: 'Modal verbs like "must" are followed by the bare infinitive (no "to").',
    category: 'Modal verbs',
  },
  {
    id: 'err-11',
    level: 'B1',
    sentence: 'I went to a Europe last summer.',
    correction: 'Europe',
    errorWord: 'a Europe',
    explanation: 'Continent names do not take an article. Use "Europe", not "a Europe".',
    category: 'Articles',
  },
  {
    id: 'err-12',
    level: 'B1',
    sentence: 'We discussed about the problem for a long time.',
    correction: 'discussed',
    errorWord: 'discussed about',
    explanation: '"Discuss" is a transitive verb and does not need "about": "we discussed the problem".',
    category: 'Common mistakes',
  },

  // ── B2 (12) ──────────────────────────────────────────────────────────────

  {
    id: 'err-13',
    level: 'B2',
    sentence: 'If I would have more money, I would travel more.',
    correction: 'had',
    errorWord: 'would have',
    explanation: 'In second conditional, the if-clause uses simple past ("had"), not "would have".',
    category: 'Conditionals',
  },
  {
    id: 'err-14',
    level: 'B2',
    sentence: 'The project has been completed by the team last week.',
    correction: 'was completed',
    errorWord: 'has been completed',
    explanation: '"Last week" marks a finished time, so use simple past passive "was completed".',
    category: 'Passive voice',
  },
  {
    id: 'err-15',
    level: 'B2',
    sentence: 'She said me that she was tired.',
    correction: 'told',
    errorWord: 'said',
    explanation: '"Say" does not take an indirect object; use "told me" instead of "said me".',
    category: 'Reported speech',
  },
  {
    id: 'err-16',
    level: 'B2',
    sentence: 'He must have forgot his keys at home.',
    correction: 'forgotten',
    errorWord: 'forgot',
    explanation: '"Must have" is followed by the past participle: "must have forgotten".',
    category: 'Modal verbs',
  },
  {
    id: 'err-17',
    level: 'B2',
    sentence: 'Unless you will not study, you will fail the exam.',
    correction: 'study',
    errorWord: 'will not study',
    explanation: '"Unless" already carries negative meaning; the clause takes a positive present simple: "Unless you study".',
    category: 'Conditionals',
  },
  {
    id: 'err-18',
    level: 'B2',
    sentence: 'The report needs to be written by tomorrow, isn\'t it?',
    correction: "doesn't it",
    errorWord: "isn't it",
    explanation: 'The auxiliary in the statement is "needs to", so the tag question is "doesn\'t it".',
    category: 'Common mistakes',
  },
  {
    id: 'err-19',
    level: 'B2',
    sentence: 'He asked where did she live.',
    correction: 'she lived',
    errorWord: 'did she live',
    explanation: 'In reported/indirect questions, word order is statement-order: "where she lived".',
    category: 'Reported speech',
  },
  {
    id: 'err-20',
    level: 'B2',
    sentence: 'This time tomorrow I will sit on a plane to Paris.',
    correction: 'will be sitting',
    errorWord: 'will sit',
    explanation: 'For an action in progress at a future time, use future continuous: "will be sitting".',
    category: 'Present tenses',
  },
  {
    id: 'err-21',
    level: 'B2',
    sentence: 'She should have went to the doctor earlier.',
    correction: 'gone',
    errorWord: 'went',
    explanation: '"Should have" requires the past participle: "should have gone".',
    category: 'Modal verbs',
  },
  {
    id: 'err-22',
    level: 'B2',
    sentence: 'The results were announced to us by the manager yesterday, who surprised everyone.',
    correction: 'which',
    errorWord: 'who',
    explanation: '"Who" refers to people; "which" refers to things or whole clauses. Use "which surprised everyone".',
    category: 'Common mistakes',
  },
  {
    id: 'err-23',
    level: 'B2',
    sentence: 'Despite of the rain, we decided to go for a walk.',
    correction: 'Despite',
    errorWord: 'Despite of',
    explanation: '"Despite" is a preposition on its own; "of" is not added after it.',
    category: 'Prepositions',
  },
  {
    id: 'err-24',
    level: 'B2',
    sentence: 'The children were make to clean their rooms.',
    correction: 'made',
    errorWord: 'make',
    explanation: 'Passive of causative "make": "were made to clean" — the past participle is "made".',
    category: 'Passive voice',
  },

  // ── C1 (6) ───────────────────────────────────────────────────────────────

  {
    id: 'err-25',
    level: 'C1',
    sentence: 'Hardly I had sat down when the phone rang.',
    correction: 'had I sat',
    errorWord: 'I had sat',
    explanation: 'After negative/restrictive adverbs like "hardly" at the start of a clause, subject and auxiliary invert: "Hardly had I sat down".',
    category: 'Word order',
  },
  {
    id: 'err-26',
    level: 'C1',
    sentence: 'The politician made a strong plea for supporting the reform.',
    correction: 'support',
    errorWord: 'supporting',
    explanation: '"Make a plea for" is followed by the bare infinitive, not a gerund: "a plea for support" or "a plea to support".',
    category: 'Common mistakes',
  },
  {
    id: 'err-27',
    level: 'C1',
    sentence: 'She is used to work long hours and rarely complains.',
    correction: 'working',
    errorWord: 'work',
    explanation: '"Be used to" expresses familiarity and is followed by a gerund (-ing): "used to working".',
    category: 'Common mistakes',
  },
  {
    id: 'err-28',
    level: 'C1',
    sentence: 'Not only he failed the test, but he also forgot to submit his assignment.',
    correction: 'did he fail',
    errorWord: 'he failed',
    explanation: '"Not only" at the start of a clause triggers subject-auxiliary inversion: "Not only did he fail".',
    category: 'Word order',
  },
  {
    id: 'err-29',
    level: 'C1',
    sentence: 'The data suggests that the economy is recovering, which is an encouraging news.',
    correction: 'encouraging',
    errorWord: 'an encouraging',
    explanation: '"News" is uncountable and does not take the article "an": simply "encouraging news".',
    category: 'Articles',
  },
  {
    id: 'err-30',
    level: 'C1',
    sentence: 'It is essential that every student submits their portfolio by Friday.',
    correction: 'submit',
    errorWord: 'submits',
    explanation: 'After "it is essential that", the subjunctive mood is used: the verb takes its base form "submit" without -s.',
    category: 'Common mistakes',
  },
]
