// Grammar exercises for EnglishSpark
// B1–B2 level, targeting Slovak learners of English

export const GRAMMAR_EXERCISES = [

  // ─── ARTICLES ────────────────────────────────────────────────────────────────

  {
    id: 'art-1',
    category: 'Articles',
    level: 'B1',
    phrase: 'She wants to become ___ doctor when she finishes university.',
    answer: ['a'],
    hint: 'Job/profession after "become" takes a/an.',
    explanation: 'We use "a/an" before a singular countable noun when talking about someone\'s job or profession.',
  },
  {
    id: 'art-2',
    category: 'Articles',
    level: 'B1',
    phrase: 'He plays ___ guitar in a band on weekends.',
    answer: ['the'],
    hint: 'Musical instruments take "the".',
    explanation: 'We use "the" before the names of musical instruments.',
  },
  {
    id: 'art-3',
    category: 'Articles',
    level: 'B1',
    phrase: 'I had ___ breakfast before leaving for work this morning.',
    answer: [''],
    hint: 'Meals usually have no article.',
    explanation: 'We do not use an article before meal names (breakfast, lunch, dinner) when used in a general sense.',
  },
  {
    id: 'art-4',
    category: 'Articles',
    level: 'B1',
    phrase: '___ Amazon is the largest river in South America.',
    answer: ['the'],
    hint: 'Rivers always take "the".',
    explanation: 'We use "the" before the names of rivers, mountain ranges, seas, and oceans.',
  },
  {
    id: 'art-5',
    category: 'Articles',
    level: 'B1',
    phrase: 'She is ___ honest person — you can always trust what she says.',
    answer: ['an'],
    hint: '"Honest" starts with a vowel sound.',
    explanation: 'We use "an" before words that begin with a vowel sound, including "honest" where the "h" is silent.',
  },
  {
    id: 'art-6',
    category: 'Articles',
    level: 'B1',
    phrase: 'He went to ___ prison for three years after the robbery.',
    answer: [''],
    hint: 'Fixed expressions: go to prison/school/hospital.',
    explanation: 'With certain institutions (prison, school, hospital, church), we omit the article when referring to their primary purpose.',
  },
  {
    id: 'art-7',
    category: 'Articles',
    level: 'B1',
    phrase: 'Can you pass me ___ salt, please?',
    answer: ['the'],
    hint: 'Specific item on the table — use "the".',
    explanation: 'We use "the" when referring to a specific item that both speaker and listener can identify, such as something on the table.',
  },
  {
    id: 'art-8',
    category: 'Articles',
    level: 'B1',
    phrase: 'I love ___ coffee, especially in the morning.',
    answer: [''],
    hint: 'Uncountable nouns in general = no article.',
    explanation: 'We do not use an article before uncountable nouns when speaking in general (I love coffee, I like music).',
  },
  {
    id: 'art-9',
    category: 'Articles',
    level: 'B2',
    phrase: 'She is ___ engineer, but her brother is ___ artist.',
    answer: ['an', 'an'],
    hint: 'Both professions need a/an; "engineer" and "artist" start with vowel sounds.',
    explanation: 'We use "an" before both "engineer" and "artist" because both words begin with a vowel sound.',
  },
  {
    id: 'art-10',
    category: 'Articles',
    level: 'B2',
    phrase: 'We visited ___ Louvre when we were in Paris last summer.',
    answer: ['the'],
    hint: 'Named museums and galleries take "the".',
    explanation: 'We use "the" before the names of museums, galleries, theatres, and other unique cultural institutions.',
  },
  {
    id: 'art-11',
    category: 'Articles',
    level: 'B2',
    phrase: '___ rich should pay higher taxes — that\'s my opinion.',
    answer: ['the'],
    hint: '"The + adjective" = a group of people.',
    explanation: '"The + adjective" (the rich, the poor, the elderly) refers to an entire group of people and is always plural.',
  },
  {
    id: 'art-12',
    category: 'Articles',
    level: 'B2',
    phrase: 'He gave ___ useful advice that I still think about today.',
    answer: [''],
    hint: '"Advice" is uncountable.',
    explanation: '"Advice" is an uncountable noun, so it never takes "a" or "an" and has no plural form.',
  },

  // ─── PRESENT TENSES ──────────────────────────────────────────────────────────

  {
    id: 'pre-1',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'I ___ (not understand) why she is so upset about it.',
    answer: ["don't understand", "do not understand"],
    hint: '"Understand" is a state verb — no continuous.',
    explanation: '"Understand" is a stative verb describing a mental state, so it cannot be used in the continuous form.',
  },
  {
    id: 'pre-2',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'Look! He ___ (wear) the same jacket as yesterday.',
    answer: ['is wearing'],
    hint: '"Look!" signals something happening right now.',
    explanation: 'We use the present continuous for actions happening at the moment of speaking, especially signalled by words like "look" or "now".',
  },
  {
    id: 'pre-3',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'She ___ (always/leave) her keys on the kitchen counter.',
    answer: ['always leaves'],
    hint: '"Always" with simple = habit.',
    explanation: 'We use the present simple with frequency adverbs (always, usually, never) to describe regular habits.',
  },
  {
    id: 'pre-4',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'Water ___ (boil) at 100 degrees Celsius.',
    answer: ['boils'],
    hint: 'Scientific facts use present simple.',
    explanation: 'We use the present simple for permanent facts, scientific truths, and things that are always true.',
  },
  {
    id: 'pre-5',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'They ___ (stay) at a hotel near the beach this week.',
    answer: ['are staying'],
    hint: '"This week" = temporary situation now.',
    explanation: 'We use the present continuous for temporary situations happening around now, even if not at the exact moment of speaking.',
  },
  {
    id: 'pre-6',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'I ___ (think) this restaurant is amazing.',
    answer: ['think'],
    hint: '"Think" as an opinion = state verb.',
    explanation: 'When "think" expresses an opinion or belief, it is a stative verb and must be used in the simple form.',
  },
  {
    id: 'pre-7',
    category: 'Present tenses',
    level: 'B1',
    phrase: 'He ___ (always/interrupt) me when I\'m trying to concentrate!',
    answer: ['is always interrupting'],
    hint: '"Always" + continuous = annoying habit.',
    explanation: 'We can use "always" with the present continuous to express irritation about a repeated, annoying behaviour.',
  },
  {
    id: 'pre-8',
    category: 'Present tenses',
    level: 'B2',
    phrase: 'This soup ___ (taste) incredible — what did you put in it?',
    answer: ['tastes'],
    hint: 'Taste as a sense = state verb.',
    explanation: '"Taste" used to describe a sensory quality is stative and takes the simple form, not the continuous.',
  },
  {
    id: 'pre-9',
    category: 'Present tenses',
    level: 'B2',
    phrase: 'The chef ___ (taste) the sauce to check if it needs more salt.',
    answer: ['is tasting'],
    hint: 'Taste as an action = continuous is fine.',
    explanation: 'When "taste" describes a deliberate action (tasting something on purpose), it can be used in the continuous form.',
  },
  {
    id: 'pre-10',
    category: 'Present tenses',
    level: 'B2',
    phrase: 'She ___ (have) a bath right now — can she call you back?',
    answer: ['is having'],
    hint: '"Have" as an activity = continuous.',
    explanation: 'When "have" is used to describe an activity (have a bath, have a party, have a look), it can be used in the continuous form.',
  },
  {
    id: 'pre-11',
    category: 'Present tenses',
    level: 'B2',
    phrase: 'I ___ (see) what you mean — the design is too complicated.',
    answer: ['see'],
    hint: '"See" = understand here, not a visual action.',
    explanation: 'When "see" means "understand", it is used as a stative verb in the simple form.',
  },

  // ─── PAST TENSES ─────────────────────────────────────────────────────────────

  {
    id: 'pas-1',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'I ___ (live) in Bratislava for five years before moving to London.',
    answer: ['lived', 'had lived'],
    hint: 'Completed period in the past.',
    explanation: 'Both past simple and past perfect are possible here; past simple is more common for a completed period of time.',
  },
  {
    id: 'pas-2',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'When I arrived, she ___ (cook) dinner in the kitchen.',
    answer: ['was cooking'],
    hint: 'Interrupted action = past continuous.',
    explanation: 'We use the past continuous for an action that was in progress when another action (past simple) interrupted it.',
  },
  {
    id: 'pas-3',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'I ___ (never/be) to Japan, but I really want to go one day.',
    answer: ["have never been", "i've never been"],
    hint: 'Life experience up to now = present perfect.',
    explanation: 'We use the present perfect for life experiences when no specific time is mentioned — the experience relates to now.',
  },
  {
    id: 'pas-4',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'She ___ (lose) her keys, so she can\'t get into her flat.',
    answer: ['has lost'],
    hint: 'Result visible in the present.',
    explanation: 'We use the present perfect when a past action has a clear result or consequence in the present.',
  },
  {
    id: 'pas-5',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'They ___ (already/leave) when I got to the party.',
    answer: ['had already left'],
    hint: 'One past action before another past action.',
    explanation: 'We use the past perfect for an action that happened before another past action or time.',
  },
  {
    id: 'pas-6',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'While we ___ (walk) home, it started to rain heavily.',
    answer: ['were walking'],
    hint: 'Background action = past continuous.',
    explanation: 'The past continuous describes the background or ongoing action, while the past simple describes the sudden event.',
  },
  {
    id: 'pas-7',
    category: 'Past tenses',
    level: 'B2',
    phrase: 'By the time the film ended, I ___ (fall) asleep on the sofa.',
    answer: ['had fallen'],
    hint: '"By the time" signals past perfect.',
    explanation: '"By the time" followed by a past simple verb requires the past perfect in the main clause.',
  },
  {
    id: 'pas-8',
    category: 'Past tenses',
    level: 'B2',
    phrase: 'He ___ (work) at that company for ten years when he got promoted.',
    answer: ['had been working'],
    hint: 'Duration before a past event = past perfect continuous.',
    explanation: 'The past perfect continuous emphasises the duration of an activity that continued up to a point in the past.',
  },
  {
    id: 'pas-9',
    category: 'Past tenses',
    level: 'B1',
    phrase: 'I ___ (see) that film last weekend — it was fantastic.',
    answer: ['saw'],
    hint: '"Last weekend" = specific past time, use simple.',
    explanation: 'We use the past simple (not present perfect) when a specific past time is mentioned.',
  },
  {
    id: 'pas-10',
    category: 'Past tenses',
    level: 'B2',
    phrase: 'She looked exhausted because she ___ (travel) for 12 hours.',
    answer: ['had been travelling', 'had been traveling'],
    hint: 'Reason for a past state = past perfect continuous.',
    explanation: 'The past perfect continuous explains why something was true in the past by describing a long preceding action.',
  },
  {
    id: 'pas-11',
    category: 'Past tenses',
    level: 'B1',
    phrase: '___ (you/ever/try) sushi before you came to Japan?',
    answer: ['had you ever tried'],
    hint: 'Experience before a past point = past perfect.',
    explanation: 'We use the past perfect to ask about experiences that happened (or did not happen) before a specific past moment.',
  },

  // ─── FUTURE FORMS ────────────────────────────────────────────────────────────

  {
    id: 'fut-1',
    category: 'Future forms',
    level: 'B1',
    phrase: 'The sky is so dark. I think it ___ (rain) soon.',
    answer: ["'s going to rain", 'is going to rain'],
    hint: 'Evidence visible now = going to.',
    explanation: 'We use "going to" for predictions based on present evidence or signs that we can already see.',
  },
  {
    id: 'fut-2',
    category: 'Future forms',
    level: 'B1',
    phrase: 'I\'m tired. I think I ___ go to bed early tonight.',
    answer: ["'ll", 'will'],
    hint: 'Spontaneous decision at the moment of speaking.',
    explanation: 'We use "will" for decisions made at the moment of speaking, not planned in advance.',
  },
  {
    id: 'fut-3',
    category: 'Future forms',
    level: 'B1',
    phrase: 'We ___ (meet) our friends for dinner on Saturday — it\'s all booked.',
    answer: ["'re meeting", 'are meeting'],
    hint: 'Fixed social arrangement = present continuous.',
    explanation: 'We use the present continuous for definite, pre-arranged plans or appointments, especially with other people.',
  },
  {
    id: 'fut-4',
    category: 'Future forms',
    level: 'B1',
    phrase: '"The phone is ringing." — "Don\'t worry, I ___ get it."',
    answer: ["'ll", 'will'],
    hint: 'Offer made on the spot.',
    explanation: 'We use "will" for spontaneous offers and decisions made at the moment of speaking.',
  },
  {
    id: 'fut-5',
    category: 'Future forms',
    level: 'B1',
    phrase: 'She ___ (study) medicine — she\'s already applied to university.',
    answer: ['is going to study'],
    hint: 'A plan already decided = going to.',
    explanation: 'We use "going to" for plans and intentions that have already been decided before the moment of speaking.',
  },
  {
    id: 'fut-6',
    category: 'Future forms',
    level: 'B2',
    phrase: 'By next year, I ___ (save) enough money for a holiday.',
    answer: ["'ll have saved", 'will have saved'],
    hint: '"By next year" signals future perfect.',
    explanation: 'We use the future perfect to describe an action that will be completed before a specific future point.',
  },
  {
    id: 'fut-7',
    category: 'Future forms',
    level: 'B2',
    phrase: 'This time tomorrow, I ___ (sit) on a beach in Greece.',
    answer: ["'ll be sitting", 'will be sitting'],
    hint: '"This time tomorrow" = future continuous.',
    explanation: 'We use the future continuous for an action that will be in progress at a specific time in the future.',
  },
  {
    id: 'fut-8',
    category: 'Future forms',
    level: 'B1',
    phrase: 'I promise I ___ call you as soon as I arrive.',
    answer: ["'ll", 'will'],
    hint: 'Promises use "will".',
    explanation: 'We use "will" to make promises and commitments about the future.',
  },
  {
    id: 'fut-9',
    category: 'Future forms',
    level: 'B2',
    phrase: 'Look at him eat — he ___ (be) sick if he carries on like that.',
    answer: ["'s going to be", 'is going to be'],
    hint: 'Certain future result based on evidence.',
    explanation: '"Going to" is used for a future outcome that seems certain based on something we can see happening right now.',
  },
  {
    id: 'fut-10',
    category: 'Future forms',
    level: 'B1',
    phrase: 'The train ___ (depart) at 9:15 according to the timetable.',
    answer: ['departs', 'is departing'],
    hint: 'Fixed scheduled event = present simple.',
    explanation: 'We use the present simple for scheduled or timetabled future events (trains, flights, showtimes).',
  },

  // ─── CONDITIONALS ────────────────────────────────────────────────────────────

  {
    id: 'con-1',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'If you ___ (heat) ice, it melts.',
    answer: ['heat'],
    hint: 'General truth / scientific fact = zero conditional.',
    explanation: 'The zero conditional uses present simple in both clauses to express general truths and facts.',
  },
  {
    id: 'con-2',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'If it ___ (not/rain) tomorrow, we\'ll have a picnic in the park.',
    answer: ["doesn't rain", 'does not rain'],
    hint: 'Real future possibility = first conditional.',
    explanation: 'The first conditional uses present simple in the if-clause and "will" in the main clause for real, possible situations.',
  },
  {
    id: 'con-3',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'If I ___ (be) rich, I would travel around the world.',
    answer: ['were', 'was'],
    hint: 'Imaginary present situation = second conditional.',
    explanation: 'The second conditional uses past simple (or "were" for all subjects) in the if-clause for unreal present situations.',
  },
  {
    id: 'con-4',
    category: 'Conditionals',
    level: 'B2',
    phrase: 'If she ___ (study) harder, she would have passed the exam.',
    answer: ['had studied'],
    hint: 'Regret about the past = third conditional.',
    explanation: 'The third conditional uses past perfect in the if-clause to talk about unreal past situations and their imagined results.',
  },
  {
    id: 'con-5',
    category: 'Conditionals',
    level: 'B2',
    phrase: 'If I had taken that job offer, I ___ (be) living in New York now.',
    answer: ['would be'],
    hint: 'Past cause + present result = mixed conditional.',
    explanation: 'Mixed conditionals combine the third conditional (past perfect if-clause) with the second conditional (would + infinitive) when a past action affects the present.',
  },
  {
    id: 'con-6',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'What would you do if you ___ (find) a wallet full of money?',
    answer: ['found'],
    hint: 'Hypothetical question = second conditional.',
    explanation: 'In second conditional questions, the if-clause uses past simple to describe a hypothetical scenario.',
  },
  {
    id: 'con-7',
    category: 'Conditionals',
    level: 'B2',
    phrase: 'If I ___ (know) her phone number, I would have called her.',
    answer: ['had known'],
    hint: 'Didn\'t know in the past = third conditional.',
    explanation: 'The third conditional refers to an imagined different past — here, not knowing the number prevented the call.',
  },
  {
    id: 'con-8',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'Unless you ___ (leave) now, you\'ll miss the last bus.',
    answer: ['leave'],
    hint: '"Unless" = "if not" — same tense rules.',
    explanation: '"Unless" means "if not" and follows the same tense rules as regular conditionals.',
  },
  {
    id: 'con-9',
    category: 'Conditionals',
    level: 'B2',
    phrase: 'I ___ (help) you move if I hadn\'t already made plans.',
    answer: ['would have helped'],
    hint: 'Past regret — you already have other plans.',
    explanation: 'When expressing that a past action prevented you from doing something, use "would have + past participle" in the main clause.',
  },
  {
    id: 'con-10',
    category: 'Conditionals',
    level: 'B1',
    phrase: 'If water ___ (reach) 100°C, it boils — that\'s just physics.',
    answer: ['reaches'],
    hint: 'Scientific fact = zero conditional.',
    explanation: 'Zero conditional uses present simple in both clauses for universal facts and scientific laws.',
  },
  {
    id: 'con-11',
    category: 'Conditionals',
    level: 'B2',
    phrase: 'Even if I ___ (be) offered the job, I don\'t think I would take it.',
    answer: ['were', 'was'],
    hint: '"Even if" + unreal = second conditional.',
    explanation: '"Even if" can be used in second conditional sentences to talk about something that is unlikely or hypothetical.',
  },

  // ─── MODAL VERBS ─────────────────────────────────────────────────────────────

  {
    id: 'mod-1',
    category: 'Modal verbs',
    level: 'B1',
    phrase: 'You ___ wear a seatbelt in the car — it\'s the law.',
    answer: ['must', 'have to'],
    hint: 'Legal obligation.',
    explanation: 'Both "must" and "have to" express strong obligation; "have to" often refers to external rules and laws.',
  },
  {
    id: 'mod-2',
    category: 'Modal verbs',
    level: 'B1',
    phrase: 'You look pale. You ___ see a doctor about that.',
    answer: ['should', 'ought to'],
    hint: 'Advice or recommendation.',
    explanation: '"Should" and "ought to" are used to give advice or make recommendations.',
  },
  {
    id: 'mod-3',
    category: 'Modal verbs',
    level: 'B1',
    phrase: 'She ___ speak three languages when she was twelve — she was incredible.',
    answer: ['could'],
    hint: 'Past ability = could.',
    explanation: 'We use "could" to talk about a general ability someone had in the past.',
  },
  {
    id: 'mod-4',
    category: 'Modal verbs',
    level: 'B1',
    phrase: 'I\'m not sure, but it ___ be true — I\'ve heard similar things before.',
    answer: ['might', 'may', 'could'],
    hint: 'Uncertainty / possibility.',
    explanation: '"Might", "may", and "could" all express uncertainty or possibility in the present or future.',
  },
  {
    id: 'mod-5',
    category: 'Modal verbs',
    level: 'B1',
    phrase: 'You ___ finish it tonight — tomorrow is fine too.',
    answer: ["needn't", 'need not', "don't need to", 'do not need to'],
    hint: 'No obligation = needn\'t / don\'t need to.',
    explanation: '"Needn\'t" and "don\'t need to" mean there is no obligation or necessity.',
  },
  {
    id: 'mod-6',
    category: 'Modal verbs',
    level: 'B2',
    phrase: 'He ___ (leave) already — his coat is gone.',
    answer: ['must have left'],
    hint: 'Logical deduction about the past.',
    explanation: '"Must have + past participle" expresses a logical deduction or conclusion about something in the past.',
  },
  {
    id: 'mod-7',
    category: 'Modal verbs',
    level: 'B2',
    phrase: 'She ___ (see) the email — she never replied.',
    answer: ["can't have seen", 'cannot have seen', "couldn't have seen"],
    hint: 'Deduction that something did NOT happen.',
    explanation: '"Can\'t have + past participle" expresses certainty that something did not happen in the past.',
  },
  {
    id: 'mod-8',
    category: 'Modal verbs',
    level: 'B2',
    phrase: 'You ___ tell anyone about this — it\'s strictly confidential.',
    answer: ["mustn't", 'must not'],
    hint: 'Prohibition = mustn\'t.',
    explanation: '"Mustn\'t" expresses prohibition — something is not allowed.',
  },
  {
    id: 'mod-9',
    category: 'Modal verbs',
    level: 'B2',
    phrase: 'He ___ (work) harder when he was younger — he might have been more successful.',
    answer: ['should have worked', 'ought to have worked'],
    hint: 'Past regret / criticism.',
    explanation: '"Should have + past participle" expresses regret or criticism about something that did not happen in the past.',
  },
  {
    id: 'mod-10',
    category: 'Modal verbs',
    level: 'B1',
    phrase: '___ I open the window? It\'s quite warm in here.',
    answer: ['shall', 'should', 'can', 'may', 'could'],
    hint: 'Offer or suggestion to do something.',
    explanation: '"Shall I...?" is commonly used to make offers or suggestions, especially in British English.',
  },
  {
    id: 'mod-11',
    category: 'Modal verbs',
    level: 'B2',
    phrase: 'You ___ be tired after such a long journey.',
    answer: ['must'],
    hint: 'Strong logical deduction about the present.',
    explanation: '"Must" expresses a confident logical conclusion or deduction based on available information.',
  },

  // ─── PASSIVE VOICE ───────────────────────────────────────────────────────────

  {
    id: 'pas_v-1',
    category: 'Passive voice',
    level: 'B1',
    phrase: 'This bridge ___ (build) in 1887.',
    answer: ['was built'],
    hint: 'Past simple passive: was/were + past participle.',
    explanation: 'The past simple passive is formed with "was/were + past participle" and is used when the agent is unknown or unimportant.',
  },
  {
    id: 'pas_v-2',
    category: 'Passive voice',
    level: 'B1',
    phrase: 'The report ___ (send) to all managers every Monday morning.',
    answer: ['is sent'],
    hint: 'Present simple passive: is/are + past participle.',
    explanation: 'The present simple passive uses "is/are + past participle" for regular, habitual actions.',
  },
  {
    id: 'pas_v-3',
    category: 'Passive voice',
    level: 'B1',
    phrase: 'The new shopping centre ___ (open) next month.',
    answer: ['will be opened', 'is going to be opened', 'is being opened'],
    hint: 'Future passive: will be + past participle.',
    explanation: 'The future passive uses "will be + past participle" for actions that will happen to something or someone.',
  },
  {
    id: 'pas_v-4',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'The suspect ___ (question) by police for several hours yesterday.',
    answer: ['was being questioned'],
    hint: 'Ongoing past action = past continuous passive.',
    explanation: 'The past continuous passive (was/were being + past participle) describes an ongoing passive action in the past.',
  },
  {
    id: 'pas_v-5',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'The new policy ___ (announce) by the CEO at the press conference.',
    answer: ['was announced'],
    hint: 'Completed past event — agent mentioned.',
    explanation: 'Even when the agent is mentioned (using "by"), we still use the passive when the focus is on the action or recipient.',
  },
  {
    id: 'pas_v-6',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'The injured players ___ (take) to hospital after the match.',
    answer: ['were taken'],
    hint: 'Multiple people = were + past participle.',
    explanation: 'When the subject is plural, the past simple passive uses "were" instead of "was".',
  },
  {
    id: 'pas_v-7',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'It is believed that the painting ___ (steal) during the renovation.',
    answer: ['was stolen'],
    hint: 'Passive infinitive after "believed that".',
    explanation: '"It is believed/reported/said that..." is a common passive construction used in news and formal writing.',
  },
  {
    id: 'pas_v-8',
    category: 'Passive voice',
    level: 'B1',
    phrase: 'My car ___ (service) right now — I had to take the bus.',
    answer: ['is being serviced'],
    hint: 'Happening at this moment = present continuous passive.',
    explanation: 'The present continuous passive (is/are being + past participle) describes a passive action in progress right now.',
  },
  {
    id: 'pas_v-9',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'The contract ___ (not/sign) yet — we\'re still negotiating.',
    answer: ["hasn't been signed", 'has not been signed'],
    hint: 'Present perfect passive: has/have been + past participle.',
    explanation: 'The present perfect passive uses "has/have been + past participle" for actions with a connection to the present.',
  },
  {
    id: 'pas_v-10',
    category: 'Passive voice',
    level: 'B2',
    phrase: 'She ___ (give) a promotion after just six months in the company.',
    answer: ['was given'],
    hint: 'Passive with indirect object as subject.',
    explanation: 'In English, the indirect object of a sentence (the person receiving something) can become the subject of a passive sentence.',
  },

  // ─── REPORTED SPEECH ─────────────────────────────────────────────────────────

  {
    id: 'rep-1',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"I love this city." → She said that she ___ that city.',
    answer: ['loved'],
    hint: '"Love" (present) → "loved" (past) in reported speech.',
    explanation: 'In reported speech, present simple usually shifts to past simple when the reporting verb is in the past.',
  },
  {
    id: 'rep-2',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"I will call you tomorrow." → He said he ___ call me the next day.',
    answer: ['would'],
    hint: '"Will" → "would" in reported speech.',
    explanation: '"Will" shifts to "would" in reported speech, and "tomorrow" shifts to "the next day".',
  },
  {
    id: 'rep-3',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"Don\'t touch that!" → She told me ___ touch it.',
    answer: ['not to'],
    hint: 'Reported imperatives: told + object + (not) to + infinitive.',
    explanation: 'Reported negative commands use "told + person + not to + infinitive".',
  },
  {
    id: 'rep-4',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"Are you coming to the party?" → She asked me if I ___ to the party.',
    answer: ['was coming'],
    hint: 'Reported yes/no question uses "if" and statement word order.',
    explanation: 'Reported yes/no questions use "if" or "whether" and normal statement word order (no auxiliary inversion).',
  },
  {
    id: 'rep-5',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"I have already eaten." → He told me he ___ already eaten.',
    answer: ['had'],
    hint: 'Present perfect → past perfect in reported speech.',
    explanation: 'The present perfect shifts to past perfect in reported speech.',
  },
  {
    id: 'rep-6',
    category: 'Reported speech',
    level: 'B2',
    phrase: '"I can\'t find my passport!" → She said she ___ find her passport.',
    answer: ["couldn't", 'could not'],
    hint: '"Can\'t" → "couldn\'t" in reported speech.',
    explanation: '"Can\'t" shifts to "couldn\'t" when backshifting in reported speech.',
  },
  {
    id: 'rep-7',
    category: 'Reported speech',
    level: 'B1',
    phrase: '"Where does she work?" → He asked me where she ___.',
    answer: ['worked'],
    hint: 'Reported Wh-question: no inversion, past tense.',
    explanation: 'Reported wh-questions use statement word order and appropriate tense backshift.',
  },
  {
    id: 'rep-8',
    category: 'Reported speech',
    level: 'B2',
    phrase: '"You should rest more," the doctor said. → The doctor advised me ___ more.',
    answer: ['to rest'],
    hint: 'Advice reported with: advised + to + infinitive.',
    explanation: 'When reporting advice, we often use "advised/told + object + to + infinitive" instead of shifting "should".',
  },
  {
    id: 'rep-9',
    category: 'Reported speech',
    level: 'B2',
    phrase: '"We were living in Paris then." → They said they ___ in Paris at that time.',
    answer: ['had been living'],
    hint: 'Past continuous → past perfect continuous in reported speech.',
    explanation: 'The past continuous shifts to the past perfect continuous in reported speech.',
  },
  {
    id: 'rep-10',
    category: 'Reported speech',
    level: 'B1',
    phrase: 'She ___ me that the meeting had been cancelled.',
    answer: ['told'],
    hint: '"Tell" needs an object; "say" does not.',
    explanation: '"Tell" must be followed by a person (told me, told her), while "say" does not take a direct personal object.',
  },

  // ─── WORD ORDER ──────────────────────────────────────────────────────────────

  {
    id: 'wor-1',
    category: 'Word order',
    level: 'B1',
    phrase: '___ your sister live in Prague?',
    answer: ['does'],
    hint: 'Yes/no question: Does/Do + subject + infinitive.',
    explanation: 'Direct questions in the present simple use "do/does" before the subject, and the main verb stays in its base form.',
  },
  {
    id: 'wor-2',
    category: 'Word order',
    level: 'B1',
    phrase: 'Could you tell me where ___ the nearest pharmacy?',
    answer: ['the nearest pharmacy is', 'is the nearest pharmacy'],
    hint: 'Indirect questions use statement word order.',
    explanation: 'In indirect/embedded questions, we use statement word order (subject + verb), not the inverted question order.',
  },
  {
    id: 'wor-3',
    category: 'Word order',
    level: 'B1',
    phrase: 'It was a ___ small old red Italian sports car.',
    answer: ['lovely', 'beautiful', 'nice', 'amazing', 'wonderful', 'great'],
    hint: 'Opinion adjectives come before size.',
    explanation: 'English adjective order is: opinion, size, age, shape, colour, origin, material — so "lovely small old red Italian".',
  },
  {
    id: 'wor-4',
    category: 'Word order',
    level: 'B1',
    phrase: 'I don\'t know why ___ so upset about it.',
    answer: ['she is', 'he is', 'they are'],
    hint: 'Embedded clause: no inversion after "why".',
    explanation: 'After question words in embedded clauses (I don\'t know why, I wonder where), use normal subject-verb order.',
  },
  {
    id: 'wor-5',
    category: 'Word order',
    level: 'B1',
    phrase: '___ they arrive before midnight last night?',
    answer: ['did'],
    hint: 'Past simple question uses "Did".',
    explanation: 'Past simple yes/no questions are formed with "Did + subject + base verb".',
  },
  {
    id: 'wor-6',
    category: 'Word order',
    level: 'B2',
    phrase: 'Do you know how long ___ to get there?',
    answer: ['it takes', 'it will take'],
    hint: 'Indirect question: subject before verb.',
    explanation: 'In indirect questions, the subject comes before the verb — there is no auxiliary inversion.',
  },
  {
    id: 'wor-7',
    category: 'Word order',
    level: 'B1',
    phrase: 'She speaks English ___.',
    answer: ['very well', 'really well', 'quite well', 'fluently', 'perfectly'],
    hint: 'Adverbs of manner come after the verb (and object).',
    explanation: 'Adverbs of manner (well, quickly, fluently) normally come after the verb or after the object if there is one.',
  },
  {
    id: 'wor-8',
    category: 'Word order',
    level: 'B2',
    phrase: 'I have no idea what time ___ yesterday.',
    answer: ['it was', 'the meeting started', 'she left', 'he arrived'],
    hint: 'After "I have no idea what", keep statement word order.',
    explanation: 'Indirect questions and "no idea" clauses use statement word order: subject + verb.',
  },
  {
    id: 'wor-9',
    category: 'Word order',
    level: 'B2',
    phrase: 'It was a ___ French rectangular wooden table.',
    answer: ['beautiful', 'lovely', 'nice', 'stunning', 'gorgeous', 'old', 'long'],
    hint: 'Opinion adjective goes first in the sequence.',
    explanation: 'The standard adjective order places opinion before shape, origin, and material.',
  },
  {
    id: 'wor-10',
    category: 'Word order',
    level: 'B1',
    phrase: '___ she working late again?',
    answer: ['is', 'was'],
    hint: 'Continuous question: be verb before subject.',
    explanation: 'Questions in the present or past continuous invert the auxiliary "be" and the subject.',
  },

  // ─── COMMON MISTAKES ─────────────────────────────────────────────────────────

  {
    id: 'mis-1',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'There isn\'t ___ milk left — can you buy some on your way home?',
    answer: ['any'],
    hint: '"Any" in negatives; "some" in positives.',
    explanation: 'We use "any" in negative sentences and questions, and "some" in positive statements.',
  },
  {
    id: 'mis-2',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'How ___ people were at the concert last night?',
    answer: ['many'],
    hint: '"Many" for countable; "much" for uncountable.',
    explanation: '"Many" is used with countable nouns (people, tickets, songs); "much" is used with uncountable nouns (money, time, water).',
  },
  {
    id: 'mis-3',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'Can you ___ me a favour and turn down the music?',
    answer: ['do'],
    hint: '"Do a favour", not "make a favour".',
    explanation: '"Do a favour" is a fixed collocation — we always use "do", not "make".',
  },
  {
    id: 'mis-4',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'She ___ a mistake in the report and had to correct it.',
    answer: ['made'],
    hint: '"Make a mistake", not "do a mistake".',
    explanation: '"Make a mistake" is the correct collocation — we always say "make" with mistake.',
  },
  {
    id: 'mis-5',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'He ___ me that the shop would be closed on Sunday.',
    answer: ['told'],
    hint: '"Tell" needs an object (told me); "say" does not (said that).',
    explanation: '"Tell" must be followed by a person (told me); "say" is used without a direct object (said that...).',
  },
  {
    id: 'mis-6',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'I was just ___ the sunset from the balcony — it was breathtaking.',
    answer: ['watching'],
    hint: '"Watch" = intentional observation; "see" = notice without trying.',
    explanation: '"Watch" implies deliberate, sustained observation, while "see" means to notice or perceive something.',
  },
  {
    id: 'mis-7',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'Could you ___ me your pen for a moment? I\'ll give it right back.',
    answer: ['lend'],
    hint: '"Lend" = give temporarily; "borrow" = take temporarily.',
    explanation: '"Lend" means to give something to someone for a time; "borrow" means to take something from someone for a time.',
  },
  {
    id: 'mis-8',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'Can I ___ a pen? I forgot mine at home.',
    answer: ['borrow'],
    hint: '"Borrow" = take from someone; "lend" = give to someone.',
    explanation: 'You "borrow" something from someone (you receive it), but you "lend" something to someone (you give it).',
  },
  {
    id: 'mis-9',
    category: 'Common mistakes',
    level: 'B2',
    phrase: 'The government plans to ___ taxes on luxury goods next year.',
    answer: ['raise', 'increase'],
    hint: '"Raise" = move something up (transitive); "rise" = go up (intransitive).',
    explanation: '"Raise" is transitive (it needs an object: raise taxes, raise a child); "rise" is intransitive (the sun rises, prices rise).',
  },
  {
    id: 'mis-10',
    category: 'Common mistakes',
    level: 'B2',
    phrase: 'The price of petrol ___ again last week.',
    answer: ['rose'],
    hint: '"Rise" is intransitive — no object.',
    explanation: '"Rise" (rose, risen) is intransitive and never takes a direct object — it means to go up by itself.',
  },
  {
    id: 'mis-11',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'I ___ a noise downstairs and went to check what it was.',
    answer: ['heard'],
    hint: '"Hear" = passive perception; "listen" = active attention.',
    explanation: '"Hear" describes passive sound perception (sounds reach your ears without effort); "listen" involves deliberate attention.',
  },
  {
    id: 'mis-12',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'She ___ to music while she was cooking dinner.',
    answer: ['listened'],
    hint: '"Listen to" = active, intentional.',
    explanation: '"Listen" is always used for intentional, active attention to sound, followed by "to".',
  },
  {
    id: 'mis-13',
    category: 'Common mistakes',
    level: 'B2',
    phrase: 'He was so ___ in the film that he forgot to eat his popcorn.',
    answer: ['absorbed', 'engrossed', 'interested'],
    hint: '"Interested in" vs "interesting" — adjective form matters.',
    explanation: '"Interested" describes how a person feels; "interesting" describes what the thing is like — do not confuse participial adjectives.',
  },
  {
    id: 'mis-14',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'She did ___ well on the test — she got 98%!',
    answer: ['really', 'very', 'so', 'surprisingly', 'incredibly', 'extremely'],
    hint: 'Do not use "very" with adverbs like "well" in informal speech? Actually you can — just pick a natural intensifier.',
    explanation: 'Adverbs like "really", "very", and "so" are commonly used to intensify adverbs of manner such as "well".',
  },
  {
    id: 'mis-15',
    category: 'Common mistakes',
    level: 'B2',
    phrase: 'I need to ___ an appointment with my dentist.',
    answer: ['make', 'schedule', 'book'],
    hint: '"Make an appointment" — colocation with "make".',
    explanation: '"Make an appointment" is the standard collocation in English — not "do" or "take" an appointment.',
  },
  {
    id: 'mis-16',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'There were ___ traffic on the motorway this morning.',
    answer: ['a lot of', 'lots of', 'so much'],
    hint: '"Traffic" is uncountable — not "many".',
    explanation: '"Traffic" is an uncountable noun in English, so you cannot say "many traffics" — use "a lot of" or "much".',
  },
  {
    id: 'mis-17',
    category: 'Common mistakes',
    level: 'B2',
    phrase: 'The news ___ very surprising — nobody expected it.',
    answer: ['was'],
    hint: '"News" is singular in English (uncountable).',
    explanation: '"News" is uncountable in English and always takes a singular verb, even though it ends in "-s".',
  },
  {
    id: 'mis-18',
    category: 'Common mistakes',
    level: 'B1',
    phrase: 'I\'m going to ___ a party for her birthday next Saturday.',
    answer: ['have', 'throw', 'organise', 'organize', 'host'],
    hint: '"Have / throw a party" — not "make" a party.',
    explanation: 'The correct collocations with "party" are "have", "throw", "organise", or "host" — never "make a party".',
  },

  // ─── GERUNDS VS INFINITIVES ──────────────────────────────────────────────────

  {
    id: 'ger-1',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'I enjoy ___ (listen) to music while I cook.',
    answer: ['listening'],
    hint: '"Enjoy" is always followed by a gerund (-ing).',
    explanation: 'After "enjoy", use the gerund (-ing form): "enjoy listening", "enjoy swimming", etc.',
  },
  {
    id: 'ger-2',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'She decided ___ (study) abroad for a year.',
    answer: ['to study'],
    hint: '"Decide" is followed by the infinitive.',
    explanation: '"Decide" is followed by to + infinitive: "decided to study", "decided to leave".',
  },
  {
    id: 'ger-3',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'He avoided ___ (make) eye contact during the interview.',
    answer: ['making'],
    hint: '"Avoid" is always followed by a gerund.',
    explanation: 'After "avoid", use the gerund (-ing form): "avoid making", "avoid eating", etc.',
  },
  {
    id: 'ger-4',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'They promised ___ (arrive) on time.',
    answer: ['to arrive'],
    hint: '"Promise" takes an infinitive.',
    explanation: '"Promise" is followed by to + infinitive: "promised to arrive", "promised to help".',
  },
  {
    id: 'ger-5',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'Would you mind ___ (open) the window?',
    answer: ['opening'],
    hint: '"Mind" is followed by a gerund.',
    explanation: 'After "mind", use the gerund: "mind opening", "mind waiting". "Would you mind...?" is a polite request.',
  },
  {
    id: 'ger-6',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'We managed ___ (finish) the project before the deadline.',
    answer: ['to finish'],
    hint: '"Manage" always takes an infinitive.',
    explanation: '"Manage" is followed by to + infinitive: "managed to finish", "managed to escape".',
  },
  {
    id: 'ger-7',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'I remember ___ (meet) her at the conference last year.',
    answer: ['meeting'],
    hint: '"Remember + gerund" = memory of a past event.',
    explanation: '"Remember + gerund" refers to remembering a past action. "Remember + infinitive" means not forgetting to do something.',
  },
  {
    id: 'ger-8',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'Please remember ___ (lock) the door when you leave.',
    answer: ['to lock'],
    hint: '"Remember + infinitive" = don\'t forget to do something.',
    explanation: '"Remember + to-infinitive" means not forgetting to do something. Compare: "I remember locking it" (past memory) vs "Remember to lock it" (future obligation).',
  },
  {
    id: 'ger-9',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'She stopped ___ (smoke) five years ago.',
    answer: ['smoking'],
    hint: '"Stop + gerund" = quit doing something.',
    explanation: '"Stop + gerund" means quitting an activity. "Stop + infinitive" means pausing in order to do something else.',
  },
  {
    id: 'ger-10',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'He stopped ___ (buy) a newspaper on his way home.',
    answer: ['to buy'],
    hint: '"Stop + infinitive" = paused in order to do something.',
    explanation: '"Stop + to-infinitive" means pausing what you are doing in order to do something else.',
  },
  {
    id: 'ger-11',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'I tried ___ (add) more salt, but it still tasted bland.',
    answer: ['adding'],
    hint: '"Try + gerund" = experiment with an action.',
    explanation: '"Try + gerund" means experimenting. "Try + infinitive" means making an effort to do something difficult.',
  },
  {
    id: 'ger-12',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'She tried ___ (contact) him, but his phone was off.',
    answer: ['to contact'],
    hint: '"Try + infinitive" = attempt to do something.',
    explanation: '"Try + to-infinitive" means attempting something. Compare: "Try calling" (experiment) vs "Try to call" (make an effort).',
  },
  {
    id: 'ger-13',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'I can\'t stand ___ (wait) in long queues.',
    answer: ['waiting'],
    hint: '"Can\'t stand" is followed by a gerund.',
    explanation: 'After "can\'t stand", "can\'t help", "can\'t bear", use the gerund form.',
  },
  {
    id: 'ger-14',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'He admitted ___ (take) the money from the drawer.',
    answer: ['taking'],
    hint: '"Admit" is followed by a gerund.',
    explanation: '"Admit", "deny", "regret" (past actions) are all followed by the gerund.',
  },
  {
    id: 'ger-15',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'They suggested ___ (take) the train instead of driving.',
    answer: ['taking'],
    hint: '"Suggest" is followed by a gerund, not an infinitive.',
    explanation: '"Suggest" is followed by the gerund or a "that" clause, never directly by a to-infinitive.',
  },
  {
    id: 'ger-16',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'I regret ___ (tell) you that the event has been cancelled.',
    answer: ['to tell'],
    hint: '"Regret + infinitive" is used in formal announcements.',
    explanation: '"Regret + to-infinitive" introduces bad news formally. "Regret + gerund" refers to regretting a past action.',
  },
  {
    id: 'ger-17',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'He went on ___ (talk) for another hour after the break.',
    answer: ['talking'],
    hint: '"Go on + gerund" = continue doing the same thing.',
    explanation: '"Go on + gerund" means continuing the same activity. "Go on + infinitive" means moving on to a new activity.',
  },
  {
    id: 'ger-18',
    category: 'Gerunds vs Infinitives',
    level: 'B2',
    phrase: 'After working in finance, she went on ___ (become) a teacher.',
    answer: ['to become'],
    hint: '"Go on + infinitive" = move on to a different activity.',
    explanation: '"Go on + to-infinitive" describes a later, different action. Compare: "went on talking" (same) vs "went on to become" (new activity).',
  },
  {
    id: 'ger-19',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'She agreed ___ (help) us move to the new flat.',
    answer: ['to help'],
    hint: '"Agree" takes an infinitive.',
    explanation: '"Agree" is followed by to + infinitive. Other verbs like "refuse", "offer", "plan", "expect" also take infinitives.',
  },
  {
    id: 'ger-20',
    category: 'Gerunds vs Infinitives',
    level: 'B1',
    phrase: 'I don\'t mind ___ (cook) if you do the washing-up.',
    answer: ['cooking'],
    hint: '"Mind" takes a gerund.',
    explanation: '"Mind" (in offers or preference questions) is always followed by the gerund form.',
  },

];
