// Phrasal verbs exercises for EnglishSpark
// B1 (20) + B2 (20) — multiple-choice, 4 options each

export const PHRASAL_VERBS_EXERCISES = [

  // ─── B1 ──────────────────────────────────────────────────────────────────────

  {
    id: 'pv-1',
    level: 'B1',
    sentence: "Don't give ___ — keep trying!",
    options: ['up', 'on', 'out', 'in'],
    answer: 0,
    phrasalVerb: 'give up',
    meaning: 'to stop trying; to quit',
    example: 'She never gave up, even when things were difficult.',
  },
  {
    id: 'pv-2',
    level: 'B1',
    sentence: 'I need to look ___ this word in the dictionary.',
    options: ['up', 'into', 'after', 'out'],
    answer: 0,
    phrasalVerb: 'look up',
    meaning: 'to search for information in a reference source',
    example: 'He looked up the train times on his phone.',
  },
  {
    id: 'pv-3',
    level: 'B1',
    sentence: 'Did you find ___ who left the message?',
    options: ['out', 'up', 'on', 'over'],
    answer: 0,
    phrasalVerb: 'find out',
    meaning: 'to discover or learn a fact',
    example: 'She found out that her flight had been cancelled.',
  },
  {
    id: 'pv-4',
    level: 'B1',
    sentence: 'The plane finally took ___ after a two-hour delay.',
    options: ['off', 'up', 'out', 'on'],
    answer: 0,
    phrasalVerb: 'take off',
    meaning: 'to leave the ground and begin to fly',
    example: 'The rocket took off at exactly 10 a.m.',
  },
  {
    id: 'pv-5',
    level: 'B1',
    sentence: 'It is cold outside — put ___ your jacket before you leave.',
    options: ['on', 'up', 'out', 'off'],
    answer: 0,
    phrasalVerb: 'put on',
    meaning: 'to place a piece of clothing on your body',
    example: 'She put on her coat and went outside.',
  },
  {
    id: 'pv-6',
    level: 'B1',
    sentence: 'We ran ___ of milk, so I went to the shop.',
    options: ['out', 'up', 'away', 'down'],
    answer: 0,
    phrasalVerb: 'run out of',
    meaning: 'to use up all of a supply of something',
    example: 'They ran out of time before they could finish the exam.',
  },
  {
    id: 'pv-7',
    level: 'B1',
    sentence: 'Please go ___; I am listening carefully.',
    options: ['on', 'up', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'go on',
    meaning: 'to continue speaking or doing something',
    example: 'The teacher asked the student to go on with his presentation.',
  },
  {
    id: 'pv-8',
    level: 'B1',
    sentence: 'Even after the interruption, the team carried ___ working.',
    options: ['on', 'out', 'up', 'off'],
    answer: 0,
    phrasalVerb: 'carry on',
    meaning: 'to continue doing something',
    example: 'Carry on — you are doing really well.',
  },
  {
    id: 'pv-9',
    level: 'B1',
    sentence: 'They set ___ a new company last year.',
    options: ['up', 'out', 'on', 'off'],
    answer: 0,
    phrasalVerb: 'set up',
    meaning: 'to start or establish an organisation, business, or system',
    example: 'She set up her own bakery after leaving her job.',
  },
  {
    id: 'pv-10',
    level: 'B1',
    sentence: 'When are you coming ___ from your trip?',
    options: ['back', 'on', 'up', 'over'],
    answer: 0,
    phrasalVerb: 'come back',
    meaning: 'to return to a place',
    example: 'He came back home exhausted after the long journey.',
  },
  {
    id: 'pv-11',
    level: 'B1',
    sentence: 'Could you pick ___ some bread on your way home?',
    options: ['up', 'on', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'pick up',
    meaning: 'to collect or buy something',
    example: 'She picked up the children from school at three o\'clock.',
  },
  {
    id: 'pv-12',
    level: 'B1',
    sentence: 'My grandmother looks ___ my cat while I am on holiday.',
    options: ['after', 'up', 'into', 'over'],
    answer: 0,
    phrasalVerb: 'look after',
    meaning: 'to take care of someone or something',
    example: 'He looked after his sick friend for a whole week.',
  },
  {
    id: 'pv-13',
    level: 'B1',
    sentence: 'Remember to turn ___ the lights when you leave the room.',
    options: ['off', 'out', 'down', 'over'],
    answer: 0,
    phrasalVerb: 'turn off',
    meaning: 'to stop a device or light from working',
    example: 'Please turn off the TV — it\'s very late.',
  },
  {
    id: 'pv-14',
    level: 'B1',
    sentence: 'I usually work ___ at the gym three times a week.',
    options: ['out', 'up', 'on', 'off'],
    answer: 0,
    phrasalVerb: 'work out',
    meaning: 'to exercise in order to improve fitness',
    example: 'She works out every morning before breakfast.',
  },
  {
    id: 'pv-15',
    level: 'B1',
    sentence: 'He grew ___ in a small village in the mountains.',
    options: ['up', 'on', 'out', 'away'],
    answer: 0,
    phrasalVerb: 'grow up',
    meaning: 'to develop from a child into an adult',
    example: 'Where did you grow up?',
  },
  {
    id: 'pv-16',
    level: 'B1',
    sentence: 'I could not wake ___ in time for the early meeting.',
    options: ['up', 'on', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'wake up',
    meaning: 'to stop sleeping; to become conscious',
    example: 'She woke up at six and immediately made coffee.',
  },
  {
    id: 'pv-17',
    level: 'B1',
    sentence: 'The issue of pay was brought ___ at the team meeting.',
    options: ['up', 'on', 'out', 'off'],
    answer: 0,
    phrasalVerb: 'bring up',
    meaning: 'to mention a topic in a conversation',
    example: 'He brought up the problem of noise during the meeting.',
  },
  {
    id: 'pv-18',
    level: 'B1',
    sentence: 'The concert was called ___ because of the storm.',
    options: ['off', 'out', 'up', 'on'],
    answer: 0,
    phrasalVerb: 'call off',
    meaning: 'to cancel a planned event',
    example: 'They called off the match due to heavy rain.',
  },
  {
    id: 'pv-19',
    level: 'B1',
    sentence: 'Do not make ___ excuses — just tell me the truth.',
    options: ['up', 'out', 'on', 'off'],
    answer: 0,
    phrasalVerb: 'make up',
    meaning: 'to invent a story or excuse',
    example: 'She made up a reason for being late.',
  },
  {
    id: 'pv-20',
    level: 'B1',
    sentence: 'My car broke ___ on the motorway this morning.',
    options: ['down', 'up', 'out', 'off'],
    answer: 0,
    phrasalVerb: 'break down',
    meaning: 'to stop working (of a machine or vehicle)',
    example: 'The printer broke down right before the presentation.',
  },

  // ─── B2 ──────────────────────────────────────────────────────────────────────

  {
    id: 'pv-21',
    level: 'B2',
    sentence: 'I came ___ an old photograph while tidying the attic.',
    options: ['across', 'up', 'over', 'out'],
    answer: 0,
    phrasalVerb: 'come across',
    meaning: 'to find or meet something or someone by chance',
    example: 'She came across a fascinating article about ancient Rome.',
  },
  {
    id: 'pv-22',
    level: 'B2',
    sentence: 'It turned ___ that he already knew the answer.',
    options: ['out', 'up', 'over', 'off'],
    answer: 0,
    phrasalVerb: 'turn out',
    meaning: 'to happen in a particular way; to be discovered',
    example: 'The event turned out to be a great success.',
  },
  {
    id: 'pv-23',
    level: 'B2',
    sentence: 'Please do not put ___ the decision any longer.',
    options: ['off', 'out', 'up', 'on'],
    answer: 0,
    phrasalVerb: 'put off',
    meaning: 'to delay or postpone something',
    example: 'He kept putting off the dentist appointment.',
  },
  {
    id: 'pv-24',
    level: 'B2',
    sentence: 'The police are looking ___ the cause of the accident.',
    options: ['into', 'up', 'after', 'over'],
    answer: 0,
    phrasalVerb: 'look into',
    meaning: 'to investigate or examine something carefully',
    example: 'The committee will look into the complaints next week.',
  },
  {
    id: 'pv-25',
    level: 'B2',
    sentence: 'The new transport policy brought ___ major changes in the city.',
    options: ['about', 'up', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'bring about',
    meaning: 'to cause something to happen',
    example: 'The reforms brought about a significant improvement in living standards.',
  },
  {
    id: 'pv-26',
    level: 'B2',
    sentence: 'The engineers carried ___ a thorough inspection of the bridge.',
    options: ['out', 'on', 'up', 'off'],
    answer: 0,
    phrasalVerb: 'carry out',
    meaning: 'to perform or complete a task',
    example: 'The team carried out the experiment successfully.',
  },
  {
    id: 'pv-27',
    level: 'B2',
    sentence: 'She came ___ with a brilliant solution to the problem.',
    options: ['up', 'out', 'across', 'over'],
    answer: 0,
    phrasalVerb: 'come up with',
    meaning: 'to think of an idea, plan, or solution',
    example: 'Can you come up with a better plan?',
  },
  {
    id: 'pv-28',
    level: 'B2',
    sentence: 'It is hard to deal ___ so many tasks at the same time.',
    options: ['with', 'out', 'up', 'on'],
    answer: 0,
    phrasalVerb: 'deal with',
    meaning: 'to handle or manage a situation or problem',
    example: 'She deals with difficult customers every day.',
  },
  {
    id: 'pv-29',
    level: 'B2',
    sentence: 'It took her months to get ___ the disappointment of failing the exam.',
    options: ['over', 'out', 'through', 'up'],
    answer: 0,
    phrasalVerb: 'get over',
    meaning: 'to recover from an illness, shock, or disappointment',
    example: 'He finally got over his fear of flying.',
  },
  {
    id: 'pv-30',
    level: 'B2',
    sentence: 'Nothing can make ___ for the years they lost.',
    options: ['up', 'out', 'over', 'off'],
    answer: 0,
    phrasalVerb: 'make up for',
    meaning: 'to compensate for something lost or missed',
    example: 'She worked extra hours to make up for leaving early.',
  },
  {
    id: 'pv-31',
    level: 'B2',
    sentence: 'I cannot put ___ with his rude behaviour any longer.',
    options: ['up', 'out', 'off', 'on'],
    answer: 0,
    phrasalVerb: 'put up with',
    meaning: 'to tolerate an unpleasant situation or person',
    example: 'I\'ve put up with the noise for months, but now enough is enough.',
  },
  {
    id: 'pv-32',
    level: 'B2',
    sentence: 'The doctors could not rule ___ the possibility of infection.',
    options: ['out', 'up', 'off', 'over'],
    answer: 0,
    phrasalVerb: 'rule out',
    meaning: 'to decide that something is not possible or suitable',
    example: 'The investigators ruled out foul play.',
  },
  {
    id: 'pv-33',
    level: 'B2',
    sentence: 'He always shows ___ in front of new people.',
    options: ['off', 'up', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'show off',
    meaning: 'to display one\'s abilities or possessions to impress others',
    example: 'She was showing off her new car to the neighbours.',
  },
  {
    id: 'pv-34',
    level: 'B2',
    sentence: 'Her confident manner made her stand ___ from the other candidates.',
    options: ['out', 'up', 'off', 'over'],
    answer: 0,
    phrasalVerb: 'stand out',
    meaning: 'to be clearly noticeable or better than the rest',
    example: 'The red building really stands out in the street.',
  },
  {
    id: 'pv-35',
    level: 'B2',
    sentence: 'She decided to take ___ photography as a hobby.',
    options: ['up', 'on', 'off', 'out'],
    answer: 0,
    phrasalVerb: 'take up',
    meaning: 'to start a new hobby, habit, or activity',
    example: 'He took up running after his doctor\'s advice.',
  },
  {
    id: 'pv-36',
    level: 'B2',
    sentence: 'The merger between the two banks fell ___ at the last minute.',
    options: ['through', 'out', 'down', 'off'],
    answer: 0,
    phrasalVerb: 'fall through',
    meaning: 'to fail to be completed; to not happen as planned',
    example: 'The deal fell through because they could not agree on the price.',
  },
  {
    id: 'pv-37',
    level: 'B2',
    sentence: 'He got ___ with cheating because no one checked his work.',
    options: ['away', 'out', 'off', 'over'],
    answer: 0,
    phrasalVerb: 'get away with',
    meaning: 'to do something wrong without being punished',
    example: 'You cannot get away with lying to your boss forever.',
  },
  {
    id: 'pv-38',
    level: 'B2',
    sentence: 'It is difficult to keep ___ with all the latest developments.',
    options: ['up', 'on', 'out', 'over'],
    answer: 0,
    phrasalVerb: 'keep up with',
    meaning: 'to progress at the same rate as someone or something',
    example: 'I find it hard to keep up with the news every day.',
  },
  {
    id: 'pv-39',
    level: 'B2',
    sentence: 'I felt let ___ when my friend cancelled our plans.',
    options: ['down', 'out', 'off', 'up'],
    answer: 0,
    phrasalVerb: 'let down',
    meaning: 'to disappoint someone by failing to do what was expected',
    example: 'The team let down their supporters with a poor performance.',
  },
  {
    id: 'pv-40',
    level: 'B2',
    sentence: 'They set ___ early to avoid the traffic.',
    options: ['off', 'out', 'up', 'away'],
    answer: 0,
    phrasalVerb: 'set off',
    meaning: 'to begin a journey',
    example: 'We set off at dawn to reach the summit before noon.',
  },
]
