export const WRITING_PROMPTS = [
  "Describe what you did today in 3 sentences.",
  "What's one thing you're looking forward to this week?",
  "Write about your favourite meal and why you love it.",
  "Describe your ideal weekend.",
  "What skill do you most want to improve and why?",
  "Write about a place you'd love to visit.",
  "What makes you happy? List 5 things.",
  "Describe your morning routine.",
  "Write about a challenge you overcame recently.",
  "What's a hobby you enjoy? Explain it simply.",
  "If you could change one thing about your daily routine, what would it be?",
  "Write about your favourite season and why.",
  "Describe a person who inspires you.",
  "What are your goals for this month?",
  "Write about a book, film, or show you enjoyed recently.",
  "Describe your city or town to someone who's never been there.",
  "What's something new you learned this week?",
  "Write about your perfect day.",
  "If you could have any superpower, what would it be?",
  "Describe a memory from your childhood.",
  "What are three things you're grateful for today?",
  "Write about your favourite way to relax.",
  "If you won the lottery, what would you do first?",
  "Describe your workspace or study space.",
  "What's your biggest dream?",
  "Write about an animal you find fascinating.",
  "What tradition do you love in your family or culture?",
  "Describe a time when you felt really proud of yourself.",
  "What's one habit you want to build and why?",
  "Write about something that made you smile today.",
]

export const SPEAKING_PROMPTS = [
  "Talk about what you plan to do this weekend.",
  "Describe your favourite food and how it's made.",
  "Talk about a film you watched recently — the plot and your opinion.",
  "Describe your hometown to a foreigner.",
  "Talk about a person you admire and why.",
  "Introduce yourself as if meeting someone new.",
  "Talk about your job or studies — what do you do day to day?",
  "Describe your perfect holiday destination.",
  "Talk about a goal you have for this year.",
  "What did you do yesterday? Tell the story out loud.",
  "Talk about a skill you're learning. How's it going?",
  "Describe the last book or podcast you enjoyed.",
  "Talk about your morning — from waking up until now.",
  "What's your opinion on social media?",
  "Talk about a sport or activity you enjoy watching or doing.",
  "Describe your family briefly.",
  "What are you most proud of in your life so far?",
  "Talk about the last time you laughed really hard.",
  "Describe a challenge you're facing and how you plan to handle it.",
  "What does success mean to you? Explain out loud.",
  "Talk about your favourite music or artist.",
  "Describe a typical Sunday for you.",
  "What would you tell your 10-year-old self?",
  "Talk about something you wish you had learned earlier.",
  "Describe your style — how do you like to dress?",
  "Talk about the best advice you ever received.",
  "What's one thing you'd like to change in the world?",
  "Describe a dish you can cook well.",
  "Talk about your favourite time of day and why.",
  "What's something people might not know about you?",
]

export function getDailyPrompt(prompts) {
  const dayIndex = Math.floor(Date.now() / 86400000) % prompts.length
  return prompts[dayIndex]
}
