// Word Families exercises for EnglishSpark
// B1 (10), B2 (12), C1 (8) — focus on form derivation from a root word

export const WORD_FAMILIES_EXERCISES = [

  // ─── B1 ──────────────────────────────────────────────────────────────────────

  {
    id: 'wf-1',
    level: 'B1',
    rootWord: 'decide',
    rootForm: 'verb',
    sentence: 'It was a very difficult ___ to make.',
    answer: 'decision',
    requiredForm: 'noun',
    family: [
      'decide (verb)',
      'decision (noun)',
      'decisive (adjective)',
      'indecisive (adjective)',
      'decisively (adverb)',
    ],
    explanation: 'The noun form of "decide" is "decision". It is formed by replacing "-de" with "-sion".',
  },
  {
    id: 'wf-2',
    level: 'B1',
    rootWord: 'succeed',
    rootForm: 'verb',
    sentence: 'Winning the competition was a great ___ for the whole team.',
    answer: 'success',
    requiredForm: 'noun',
    family: [
      'succeed (verb)',
      'success (noun)',
      'successful (adjective)',
      'unsuccessful (adjective)',
      'successfully (adverb)',
    ],
    explanation: '"Success" is the noun form of "succeed". Note the spelling change: the "-eed" ending becomes "-ess".',
  },
  {
    id: 'wf-3',
    level: 'B1',
    rootWord: 'apply',
    rootForm: 'verb',
    sentence: 'Have you filled in the job ___ form yet?',
    answer: 'application',
    requiredForm: 'noun',
    family: [
      'apply (verb)',
      'application (noun)',
      'applicant (noun – person)',
      'applicable (adjective)',
    ],
    explanation: '"Application" is the noun of "apply". The "-y" changes to "-ication".',
  },
  {
    id: 'wf-4',
    level: 'B1',
    rootWord: 'care',
    rootForm: 'noun/verb',
    sentence: 'The nurse was very ___ with the elderly patient.',
    answer: 'careful',
    requiredForm: 'adjective',
    family: [
      'care (noun / verb)',
      'careful (adjective)',
      'careless (adjective)',
      'carefully (adverb)',
      'carelessly (adverb)',
    ],
    explanation: '"Careful" is the adjective formed from "care" by adding the suffix "-ful".',
  },
  {
    id: 'wf-5',
    level: 'B1',
    rootWord: 'create',
    rootForm: 'verb',
    sentence: 'The artist showed a lot of ___ in her paintings.',
    answer: 'creativity',
    requiredForm: 'noun',
    family: [
      'create (verb)',
      'creation (noun)',
      'creativity (noun – quality)',
      'creative (adjective)',
      'creatively (adverb)',
    ],
    explanation: '"Creativity" is the abstract noun describing the quality of being creative, formed with the suffix "-ity".',
  },
  {
    id: 'wf-6',
    level: 'B1',
    rootWord: 'explain',
    rootForm: 'verb',
    sentence: 'The teacher gave a clear ___ of the grammar rule.',
    answer: 'explanation',
    requiredForm: 'noun',
    family: [
      'explain (verb)',
      'explanation (noun)',
      'explanatory (adjective)',
    ],
    explanation: '"Explanation" is the noun of "explain". The "-ain" ending becomes "-anation".',
  },
  {
    id: 'wf-7',
    level: 'B1',
    rootWord: 'imagine',
    rootForm: 'verb',
    sentence: 'She has a very active ___; she loves writing stories.',
    answer: 'imagination',
    requiredForm: 'noun',
    family: [
      'imagine (verb)',
      'imagination (noun)',
      'imaginative (adjective)',
      'unimaginative (adjective)',
    ],
    explanation: '"Imagination" is the noun of "imagine", formed by dropping the "-e" and adding "-ation".',
  },
  {
    id: 'wf-8',
    level: 'B1',
    rootWord: 'improve',
    rootForm: 'verb',
    sentence: 'There has been a big ___ in his pronunciation this month.',
    answer: 'improvement',
    requiredForm: 'noun',
    family: [
      'improve (verb)',
      'improvement (noun)',
      'improved (adjective)',
    ],
    explanation: '"Improvement" is formed by adding "-ment" to "improve" (dropping the final "-e").',
  },
  {
    id: 'wf-9',
    level: 'B1',
    rootWord: 'know',
    rootForm: 'verb',
    sentence: 'She has a broad ___ of European history.',
    answer: 'knowledge',
    requiredForm: 'noun',
    family: [
      'know (verb)',
      'knowledge (noun)',
      'knowledgeable (adjective)',
      'known (adjective)',
      'unknown (adjective)',
    ],
    explanation: '"Knowledge" is an irregular noun form of "know". It cannot be predicted from the verb alone.',
  },
  {
    id: 'wf-10',
    level: 'B1',
    rootWord: 'manage',
    rootForm: 'verb',
    sentence: 'She was promoted to ___ of the sales department.',
    answer: 'manager',
    requiredForm: 'noun (person)',
    family: [
      'manage (verb)',
      'manager (noun – person)',
      'management (noun – concept)',
      'manageable (adjective)',
    ],
    explanation: '"Manager" refers to the person who manages, formed by adding "-r" to "manage".',
  },

  // ─── B2 ──────────────────────────────────────────────────────────────────────

  {
    id: 'wf-11',
    level: 'B2',
    rootWord: 'organize',
    rootForm: 'verb',
    sentence: 'The conference was run very ___; everything went smoothly.',
    answer: 'organizationally',
    requiredForm: 'adverb',
    family: [
      'organize (verb)',
      'organization (noun)',
      'organizational (adjective)',
      'organizationally (adverb)',
    ],
    explanation: '"Organizationally" is the adverb from "organizational", itself derived from "organization" + "-al". Add "-ly" for the adverb.',
  },
  {
    id: 'wf-12',
    level: 'B2',
    rootWord: 'persist',
    rootForm: 'verb',
    sentence: 'Despite all the difficulties, her ___ finally paid off.',
    answer: 'persistence',
    requiredForm: 'noun',
    family: [
      'persist (verb)',
      'persistence (noun)',
      'persistent (adjective)',
      'persistently (adverb)',
    ],
    explanation: '"Persistence" is formed from the adjective "persistent" by replacing "-ent" with "-ence".',
  },
  {
    id: 'wf-13',
    level: 'B2',
    rootWord: 'rely',
    rootForm: 'verb',
    sentence: 'Old equipment is often ___, breaking down at the worst moment.',
    answer: 'unreliable',
    requiredForm: 'adjective (negative)',
    family: [
      'rely (verb)',
      'reliable (adjective)',
      'unreliable (adjective – negative)',
      'reliability (noun)',
      'reliably (adverb)',
    ],
    explanation: '"Unreliable" is the negative form of "reliable". The prefix "un-" negates the adjective.',
  },
  {
    id: 'wf-14',
    level: 'B2',
    rootWord: 'satisfy',
    rootForm: 'verb',
    sentence: 'The customer complained because the service was completely ___.',
    answer: 'unsatisfactory',
    requiredForm: 'adjective (negative)',
    family: [
      'satisfy (verb)',
      'satisfaction (noun)',
      'satisfactory (adjective)',
      'unsatisfactory (adjective – negative)',
      'satisfactorily (adverb)',
    ],
    explanation: '"Unsatisfactory" uses the prefix "un-" to negate "satisfactory". Note the "-ory" suffix on the adjective.',
  },
  {
    id: 'wf-15',
    level: 'B2',
    rootWord: 'communicate',
    rootForm: 'verb',
    sentence: 'The CEO is known for being open and ___ with all employees.',
    answer: 'communicative',
    requiredForm: 'adjective',
    family: [
      'communicate (verb)',
      'communication (noun)',
      'communicative (adjective)',
      'communicatively (adverb)',
    ],
    explanation: '"Communicative" is an adjective formed by replacing the "-ion" of "communication" with "-ive".',
  },
  {
    id: 'wf-16',
    level: 'B2',
    rootWord: 'compete',
    rootForm: 'verb',
    sentence: 'The market is highly ___; prices drop every year.',
    answer: 'competitive',
    requiredForm: 'adjective',
    family: [
      'compete (verb)',
      'competition (noun)',
      'competitive (adjective)',
      'competitively (adverb)',
      'competitor (noun – person)',
    ],
    explanation: '"Competitive" is the adjective from "compete", formed via "competition" → replace "-ion" with "-ive".',
  },
  {
    id: 'wf-17',
    level: 'B2',
    rootWord: 'cooperate',
    rootForm: 'verb',
    sentence: 'The two countries signed a ___ agreement on climate change.',
    answer: 'cooperative',
    requiredForm: 'adjective',
    family: [
      'cooperate (verb)',
      'cooperation (noun)',
      'cooperative (adjective)',
      'cooperatively (adverb)',
    ],
    explanation: '"Cooperative" (adjective) is built from "cooperate" by replacing the final "-e" with "-ive".',
  },
  {
    id: 'wf-18',
    level: 'B2',
    rootWord: 'criticize',
    rootForm: 'verb',
    sentence: 'The report offered a detailed ___ of the government\'s policy.',
    answer: 'criticism',
    requiredForm: 'noun',
    family: [
      'criticize (verb)',
      'criticism (noun)',
      'critic (noun – person)',
      'critical (adjective)',
      'critically (adverb)',
    ],
    explanation: '"Criticism" is the noun formed from "critic" + "-ism", related to the verb "criticize".',
  },
  {
    id: 'wf-19',
    level: 'B2',
    rootWord: 'embarrass',
    rootForm: 'verb',
    sentence: 'He turned red with ___ when he forgot his lines on stage.',
    answer: 'embarrassment',
    requiredForm: 'noun',
    family: [
      'embarrass (verb)',
      'embarrassment (noun)',
      'embarrassing (adjective)',
      'embarrassed (adjective – feeling)',
      'embarrassingly (adverb)',
    ],
    explanation: '"Embarrassment" is formed by adding "-ment" to "embarrass". Note the double "r" and double "s".',
  },
  {
    id: 'wf-20',
    level: 'B2',
    rootWord: 'encourage',
    rootForm: 'verb',
    sentence: 'Her teacher\'s ___ helped her believe in herself.',
    answer: 'encouragement',
    requiredForm: 'noun',
    family: [
      'encourage (verb)',
      'encouragement (noun)',
      'encouraging (adjective)',
      'discourage (verb – opposite)',
      'discouragement (noun – opposite)',
    ],
    explanation: '"Encouragement" is formed by adding "-ment" to "encourage". The opposite is "discouragement" (prefix "dis-").',
  },
  {
    id: 'wf-21',
    level: 'B2',
    rootWord: 'investigate',
    rootForm: 'verb',
    sentence: 'The police launched a full ___ into the incident.',
    answer: 'investigation',
    requiredForm: 'noun',
    family: [
      'investigate (verb)',
      'investigation (noun)',
      'investigative (adjective)',
      'investigator (noun – person)',
    ],
    explanation: '"Investigation" is the noun of "investigate", formed by dropping "-e" and adding "-ion".',
  },
  {
    id: 'wf-22',
    level: 'B2',
    rootWord: 'negotiate',
    rootForm: 'verb',
    sentence: 'After weeks of talks, both sides reached a ___ settlement.',
    answer: 'negotiated',
    requiredForm: 'adjective (past participle)',
    family: [
      'negotiate (verb)',
      'negotiation (noun)',
      'negotiator (noun – person)',
      'negotiated (adjective)',
      'non-negotiable (adjective)',
    ],
    explanation: '"Negotiated" functions as an adjective (past participle) meaning "agreed through negotiation".',
  },

  // ─── C1 ──────────────────────────────────────────────────────────────────────

  {
    id: 'wf-23',
    level: 'C1',
    rootWord: 'perceive',
    rootForm: 'verb',
    sentence: 'Her ___ of the situation turned out to be completely wrong.',
    answer: 'perception',
    requiredForm: 'noun',
    family: [
      'perceive (verb)',
      'perception (noun)',
      'perceptive (adjective)',
      'perceptively (adverb)',
      'imperceptible (adjective – too small to notice)',
    ],
    explanation: '"Perception" is the noun of "perceive", formed by replacing "-eive" with "-eption". Compare with "conceive → conception".',
  },
  {
    id: 'wf-24',
    level: 'C1',
    rootWord: 'significant',
    rootForm: 'adjective',
    sentence: 'Her contribution to the project ___ improved the final outcome.',
    answer: 'significantly',
    requiredForm: 'adverb',
    family: [
      'signify (verb)',
      'significance (noun)',
      'significant (adjective)',
      'significantly (adverb)',
      'insignificant (adjective – negative)',
    ],
    explanation: '"Significantly" is the adverb formed from "significant" + "-ly". "Insignificant" is its negative adjective (prefix "in-").',
  },
  {
    id: 'wf-25',
    level: 'C1',
    rootWord: 'transparent',
    rootForm: 'adjective',
    sentence: 'The government promised greater ___ in its decision-making.',
    answer: 'transparency',
    requiredForm: 'noun',
    family: [
      'transparent (adjective)',
      'transparency (noun)',
      'transparently (adverb)',
      'opaque (adjective – antonym)',
    ],
    explanation: '"Transparency" is the noun from "transparent", replacing "-ent" with "-ency". This "-ency" suffix is common in abstract nouns.',
  },
  {
    id: 'wf-26',
    level: 'C1',
    rootWord: 'vulnerable',
    rootForm: 'adjective',
    sentence: 'Children in conflict zones face extreme ___ to exploitation.',
    answer: 'vulnerability',
    requiredForm: 'noun',
    family: [
      'vulnerable (adjective)',
      'vulnerability (noun)',
      'invulnerable (adjective – negative)',
      'invulnerability (noun – negative)',
    ],
    explanation: '"Vulnerability" is formed from "vulnerable" by replacing "-ble" with "-bility". The prefix "in-" creates the opposite.',
  },
  {
    id: 'wf-27',
    level: 'C1',
    rootWord: 'contradict',
    rootForm: 'verb',
    sentence: 'There is an obvious ___ between what he says and what he does.',
    answer: 'contradiction',
    requiredForm: 'noun',
    family: [
      'contradict (verb)',
      'contradiction (noun)',
      'contradictory (adjective)',
      'self-contradictory (adjective)',
    ],
    explanation: '"Contradiction" is formed from "contradict" + "-ion". "Contradictory" (adjective) adds the "-ory" suffix to the noun base.',
  },
  {
    id: 'wf-28',
    level: 'C1',
    rootWord: 'distinguish',
    rootForm: 'verb',
    sentence: 'The two dialects are almost ___; even native speakers struggle.',
    answer: 'indistinguishable',
    requiredForm: 'adjective (negative)',
    family: [
      'distinguish (verb)',
      'distinguishable (adjective)',
      'indistinguishable (adjective – negative)',
      'distinguished (adjective – eminent)',
      'distinction (noun)',
    ],
    explanation: '"Indistinguishable" = prefix "in-" + "distinguishable" (from "distinguish" + "-able"). Means impossible to tell apart.',
  },
  {
    id: 'wf-29',
    level: 'C1',
    rootWord: 'emphasize',
    rootForm: 'verb',
    sentence: 'The report placed special ___ on the need for immediate action.',
    answer: 'emphasis',
    requiredForm: 'noun',
    family: [
      'emphasize (verb)',
      'emphasis (noun)',
      'emphatic (adjective)',
      'emphatically (adverb)',
    ],
    explanation: '"Emphasis" is an irregular noun (Greek origin) related to "emphasize". Its plural is "emphases". The adjective "emphatic" is less predictable.',
  },
  {
    id: 'wf-30',
    level: 'C1',
    rootWord: 'produce',
    rootForm: 'verb',
    sentence: 'The factory increased its ___ capacity by 40% last year.',
    answer: 'productive',
    requiredForm: 'adjective',
    family: [
      'produce (verb)',
      'product (noun)',
      'production (noun)',
      'productive (adjective)',
      'unproductive (adjective – negative)',
      'productivity (noun – quality)',
      'productively (adverb)',
    ],
    explanation: '"Productive" is formed from "product" + "-ive". Its negative is "unproductive" (prefix "un-"), and the noun quality is "productivity".',
  },
]
